// lib/stockUniverse.ts
export interface StockMeta {
    symbol: string;
    name: string;
  }
  
  export const POPULAR_STOCKS: StockMeta[] = [
    { symbol: "AAPL", name: "Apple Inc." },
    { symbol: "MSFT", name: "Microsoft Corp." },
    { symbol: "GOOGL", name: "Alphabet Inc." },
    { symbol: "AMZN", name: "Amazon.com Inc." },
    { symbol: "META", name: "Meta Platforms Inc." },
    { symbol: "TSLA", name: "Tesla Inc." },
    { symbol: "NVDA", name: "NVIDIA Corp." },
    { symbol: "NFLX", name: "Netflix Inc." },
    { symbol: "AMD", name: "Advanced Micro Devices" },
    { symbol: "INTC", name: "Intel Corp." },
    { symbol: "ADBE", name: "Adobe Inc." },
    { symbol: "PYPL", name: "PayPal Holdings" },
    { symbol: "CSCO", name: "Cisco Systems" },
    { symbol: "ORCL", name: "Oracle Corp." },
    { symbol: "IBM", name: "IBM" },
    { symbol: "CRM", name: "Salesforce" },
    { symbol: "QCOM", name: "Qualcomm" },
    { symbol: "TXN", name: "Texas Instruments" },
    { symbol: "SAP", name: "SAP SE" },
    { symbol: "UBER", name: "Uber Technologies" },
    { symbol: "LYFT", name: "Lyft Inc." },
    { symbol: "SHOP", name: "Shopify Inc." },
    { symbol: "SQ", name: "Block Inc." },
    { symbol: "ZM", name: "Zoom Video" },
    { symbol: "DOCU", name: "DocuSign" },
    { symbol: "SPOT", name: "Spotify Technology" },
    { symbol: "TWTR", name: "Twitter" },
    { symbol: "SNAP", name: "Snap Inc." },
    { symbol: "BABA", name: "Alibaba Group" },
    { symbol: "JD", name: "JD.com" },
    { symbol: "PDD", name: "Pinduoduo" },
    { symbol: "TCEHY", name: "Tencent Holdings" },
    { symbol: "NVAX", name: "Novavax" },
    { symbol: "MRNA", name: "Moderna" },
    { symbol: "BNTX", name: "BioNTech" },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
    { symbol: "GILD", name: "Gilead Sciences" },
    { symbol: "AMGN", name: "Amgen Inc." },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
    { symbol: "ABBV", name: "AbbVie Inc." },
    { symbol: "BIIB", name: "Biogen Inc." },
    { symbol: "CRSP", name: "CRISPR Therapeutics" },
    { symbol: "SHOP", name: "Shopify Inc." },
    { symbol: "BIDU", name: "Baidu Inc." },
    { symbol: "NVDA", name: "NVIDIA Corp." },
    { symbol: "AMD", name: "Advanced Micro Devices" },
    { symbol: "INTU", name: "Intuit Inc." },
    { symbol: "ADSK", name: "Autodesk Inc." },
    { symbol: "EA", name: "Electronic Arts" },
    { symbol: "ATVI", name: "Activision Blizzard" },
    { symbol: "ROKU", name: "Roku Inc." },
    { symbol: "SNOW", name: "Snowflake Inc." },
    { symbol: "COIN", name: "Coinbase" },
    { symbol: "PLTR", name: "Palantir Technologies" },
    { symbol: "UBER", name: "Uber Technologies" },
    { symbol: "LYFT", name: "Lyft Inc." },
    { symbol: "TWLO", name: "Twilio Inc." },
    { symbol: "DOCU", name: "DocuSign" },
    { symbol: "SPOT", name: "Spotify Technology" },
    { symbol: "SNAP", name: "Snap Inc." },
    { symbol: "BABA", name: "Alibaba Group" },
    { symbol: "JD", name: "JD.com" },
    { symbol: "PDD", name: "Pinduoduo" },
    { symbol: "TCEHY", name: "Tencent Holdings" },
    { symbol: "NVAX", name: "Novavax" },
    { symbol: "MRNA", name: "Moderna" },
    { symbol: "BNTX", name: "BioNTech" },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
    { symbol: "GILD", name: "Gilead Sciences" },
    { symbol: "AMGN", name: "Amgen Inc." },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
    { symbol: "ABBV", name: "AbbVie Inc." },
    { symbol: "BIIB", name: "Biogen Inc." },
    { symbol: "CRSP", name: "CRISPR Therapeutics" },
    { symbol: "F", name: "Ford Motor" },
    { symbol: "GM", name: "General Motors" },
    { symbol: "TSM", name: "Taiwan Semiconductor" },
    { symbol: "SONY", name: "Sony Group" },
    { symbol: "SHOP", name: "Shopify Inc." },
    { symbol: "AMD", name: "Advanced Micro Devices" },
    { symbol: "NVDA", name: "NVIDIA Corp." },
    { symbol: "AAL", name: "American Airlines" },
    { symbol: "DAL", name: "Delta Airlines" },
    { symbol: "LUV", name: "Southwest Airlines" },
    { symbol: "BA", name: "Boeing Co." },
    { symbol: "UAL", name: "United Airlines" },
    { symbol: "NKE", name: "Nike Inc." },
    { symbol: "SBUX", name: "Starbucks Corp." },
    { symbol: "DIS", name: "Disney" },
    { symbol: "MCD", name: "McDonald's Corp." },
    { symbol: "YUM", name: "Yum! Brands" },
    { symbol: "KO", name: "Coca-Cola" },
    { symbol: "PEP", name: "PepsiCo" },
    { symbol: "V", name: "Visa Inc." },
    { symbol: "MA", name: "Mastercard" },
    { symbol: "PYPL", name: "PayPal Holdings" },
    { symbol: "SQ", name: "Block Inc." },
    { symbol: "SHOP", name: "Shopify Inc." },
    { symbol: "CRM", name: "Salesforce" },
    { symbol: "INTU", name: "Intuit Inc." },
  ];
  